### PR TITLE
feat(contributors): Added contributors

### PR DESCRIPTION
**Pull request by realSaddy**
#7

### CODE REVIEW

**Comment by Oj18** [comment]
Could you move it under thanks header, and you need to do `<h6>Contributors</h6>`, not `###`, it's HTML, not Markdown.

But thanks! :)

**Comment by realSaddy** [comment]
@Oj18 Is this what you mean? Sorry, I don't quite understand what you mean by "thanks header"; thank you 😃)

**Comment by Oj18** [comment]
Not actually, sorry. What I mean is that there's an already existing header called thanks, it currently has the dictionaries used in it. It would be great if you could put it in there (as `h6` like the rest) so it could be a bit more organised. Thanks again! :)

**Comment by realSaddy** [comment]
Ooooooh, I've been doing the wrong thing this entire time. Here I'll fix it up for you lol

**Comment by realSaddy** [comment]
Here, how does this look? I'm open to change it however you like :)
image

**Comment by Oj18** [comment]
Oh sorry, didn't even see that you were able editing the wrong file! Haha, my fault.

It looks great, thanks! I'll merge now, and update the live site.

**Pull request merged**
