### PR TITLE
Fix layout bug:

### PR DESCRIPTION
**Pull request by talitaoliveira**
Pull request related to Issue #4 
- **Status text** align with **icon**

I couldn't reproduce the **Dropdown text** bug either in chrome or firefox or safari.
Here seems ok.

TODO:
- [ ] Directions to reproduce bug of **Dropdown text**

### CODE REVIEW

**Comment by Oj18** [comment]
Thanks for the pull request! All I did was open [the app](https://txttosl.oojmed.com) in Firefox (Nightly), and got these results.

Screenshot

**Comment by Oj18** [comment]
I can merge your pull now or wait if you want to work on it a bit more.

**Comment by talitaoliveira** [comment]
That's weird...
I've run the app (the link that you send) on firefox and I still cannot see this behavior..
Let me try download this firefox that you are using.
image

**Comment by Oj18** [comment]
Weird, if you want you can give up for now and I'll merge the patch for the status text.

**Comment by talitaoliveira** [comment]
Ok. You can merge.

**Pull request merged**
